import Link from "next/link";
import { requireProfile } from "@/lib/auth/profile";
import { createClient } from "@/lib/supabase/server";
import AttendanceStudentVisibility from "./attendance-student-visibility";
import AttendanceRenewalEnhancer from "./attendance-renewal-enhancer";
import "./session-attendance.css";
import "./session-attendance-nav.css";
import "./session-attendance-alerts.css";
import "./session-attendance-mobile-polish.css";
import "./session-attendance-card-polish.css";
export const dynamic="force-dynamic";
const Icon=({name}:{name:"back"|"today"|"month"|"history"})=>{const common={width:20,height:20,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.9,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(name==="back")return <svg {...common}><path d="M15 18l-6-6 6-6"/><path d="M9 12h10"/></svg>;if(name==="today")return <svg {...common}><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/><path d="M9 15l2 2 4-4"/></svg>;if(name==="month")return <svg {...common}><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01M16 18h.01"/></svg>;return <svg {...common}><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/></svg>};
export default async function AttendancePage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const params=await searchParams;const profile=await requireProfile(["owner","admin","branch_manager","registration_staff","accounting","coach"]);const organizationId=profile.organization_id;const supabase=await createClient();if(!organizationId)return <main style={{minHeight:"100vh",padding:32,background:"#f4f7fb",color:"#10213a"}}><h1>Yoklama</h1><p>Organizasyon bilgisi bulunamadı.</p><Link href="/">← Yönetim Paneline Dön</Link></main>;
const [branches,groups,schedules,memberships,students,enrollments,compensation,profiles,levels,attendanceHistory,staffAssignments]=await Promise.all([supabase.from("branches").select("id,name,short_name").eq("organization_id",organizationId).eq("is_active",true).order("name"),supabase.from("training_groups").select("id,branch_id,level_id,name,course_type,capacity,primary_coach_id,is_active").eq("organization_id",organizationId).eq("is_active",true).order("sort_order"),supabase.from("lesson_schedules").select("id,branch_id,group_id,coach_id,weekday,start_time,end_time,is_active").eq("organization_id",organizationId).eq("is_active",true).order("weekday").order("start_time"),supabase.from("student_group_memberships").select("student_id,group_id,level_id,is_active").eq("organization_id",organizationId).eq("is_active",true),supabase.from("students").select("id,first_name,last_name,student_number,status,phone,guardian_name,guardian_phone,swimming_level,medical_note,general_note").eq("organization_id",organizationId).eq("is_deleted",false).order("first_name"),supabase.from("student_enrollments").select("*").eq("organization_id",organizationId).eq("status","active"),supabase.from("student_compensation_lessons").select("student_id,target_group_id,target_schedule_id,lesson_date,status").eq("organization_id",organizationId).eq("status","planned"),supabase.from("profiles").select("id,full_name").eq("organization_id",organizationId),supabase.from("swimming_levels").select("id,name").eq("organization_id",organizationId).order("sort_order"),supabase.from("attendance_records").select("student_id,group_id,lesson_date,status").eq("organization_id",organizationId).order("lesson_date",{ascending:false}).limit(3000),supabase.from("lesson_staff_assignments").select("schedule_id,group_id,coach_id,sort_order,is_active").eq("organization_id",organizationId).eq("is_active",true).order("sort_order")]);const error=branches.error||groups.error||schedules.error||memberships.error||students.error||enrollments.error||compensation.error||profiles.error||levels.error||attendanceHistory.error||staffAssignments.error;if(error)return <main style={{minHeight:"100vh",padding:32,background:"#f4f7fb",color:"#10213a"}}><h1>Yoklama</h1><div style={{marginTop:18,padding:18,background:"#fff",border:"1px solid #fecaca",borderRadius:14,color:"#991b1b"}}>Veriler yüklenemedi: {error.message}</div></main>;
return <><nav className="saTopNav" aria-label="Yoklama hızlı erişim"><Link href="/operasyon-plani" className="saTopNavItem"><span className="saTopNavIcon"><Icon name="back"/></span><span><b>Geri</b><small>Operasyon</small></span></Link><Link href="/yoklama" className="saTopNavItem active"><span className="saTopNavIcon"><Icon name="today"/></span><span><b>Bugün</b><small>Günlük yoklama</small></span></Link><Link href="/yoklama/aylik" className="saTopNavItem"><span className="saTopNavIcon"><Icon name="month"/></span><span><b>Tüm Ay</b><small>Aylık görünüm</small></span></Link><Link href="/yoklama/gecmis" className="saTopNavItem"><span className="saTopNavIcon"><Icon name="history"/></span><span><b>Geçmiş</b><small>Ders kayıtları</small></span></Link></nav><AttendanceRenewalEnhancer students={students.data||[]}/><AttendanceStudentVisibility branches={branches.data||[]} groups={groups.data||[]} schedules={schedules.data||[]} memberships={memberships.data||[]} students={students.data||[]} enrollments={enrollments.data||[]} compensationLessons={compensation.data||[]} profiles={profiles.data||[]} levels={levels.data||[]} attendanceHistory={attendanceHistory.data||[]} staffAssignments={staffAssignments.data||[]} initialBranchId={params.branchId||""}/></>}
