"use client";

import { useMemo, useState } from "react";
import { closeFacility, startFacility } from "./tesis-sezon-actions";

export type FacilityOption={id:string;name:string};
export type GroupOption={id:string;branch_id:string;name:string};
export type PauseOption={id:string;branch_id:string;closure_date:string;estimated_open_date?:string|null;affected?:number};

export default function TesisSezonYonetimi({branches,groups,pauses=[]}:{branches:FacilityOption[];groups:GroupOption[];pauses?:PauseOption[]}){
 const [mode,setMode]=useState<"close"|"start"|"transfer">("close");
 const [source,setSource]=useState(""); const [target,setTarget]=useState("");
 const [pending,setPending]=useState(false); const [result,setResult]=useState("");
 const activePause=pauses.find(p=>p.branch_id===source);
 const branchGroups=useMemo(()=>groups.filter(g=>g.branch_id===(mode==="transfer"?target:source)),[groups,mode,source,target]);
 async function submit(fd:FormData){setPending(true);setResult("");try{const r=mode==="close"?await closeFacility(fd):await startFacility(fd);setResult(`İşlem tamamlandı. ${r.affected} kursiyerin ders planı güncellendi.`);}catch(e:any){setResult(e?.message||"İşlem tamamlanamadı.");}finally{setPending(false)}}
 return <section className="facilityOps">
  <div className="facilityOpsHead"><div><span>TESİS & SEZON YÖNETİMİ</span><h2>Havuz kapanışlarını ve yeniden başlangıçları tek yerden yönetin</h2><p>Kapanışta kalan ders hakları dondurulur. START verildiğinde haklar gerçek ders günlerine göre yeniden planlanır.</p></div><div className="facilityStatus">DERS HAKKI KORUMALI</div></div>
  {pauses.length>0&&<div className="pauseList">{pauses.map(p=><div className="pauseCard" key={p.id}><b>● KAPALI · START BEKLİYOR</b><span>{branches.find(b=>b.id===p.branch_id)?.name||"Tesis"}</span><small>Kapanış: {p.closure_date}{p.estimated_open_date?` · Tahmini açılış: ${p.estimated_open_date}`:""}{typeof p.affected==="number"?` · ${p.affected} kursiyer`:""}</small></div>)}</div>}
  <div className="facilityModes"><button type="button" className={mode==="close"?"active danger":""} onClick={()=>setMode("close")}>● Tesis / Sezonu Kapat</button><button type="button" className={mode==="start"?"active start":""} onClick={()=>setMode("start")}>▶ START Ver</button><button type="button" className={mode==="transfer"?"active transfer":""} onClick={()=>setMode("transfer")}>↗ Aktar + START Ver</button></div>
  <form action={submit} className="facilityForm">
   <label>{mode==="transfer"?"Kaynak havuz / şube":"Havuz / şube"}<select name="branch_id" required value={source} onChange={e=>setSource(e.target.value)}><option value="">Seçiniz</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
   {mode==="close"?<><label>Kapanış tarihi<input type="date" name="closure_date" required/></label><label>Tahmini açılış <small>(opsiyonel)</small><input type="date" name="estimated_open_date"/></label><label className="wide">Yönetici notu<input name="note" placeholder="Bakım, sezon arası, tesis kararı..."/></label></>:<><input type="hidden" name="pause_id" value={activePause?.id||""}/>{mode==="transfer"&&<label>Hedef havuz / şube<select name="target_branch_id" required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Seçiniz</option>{branches.filter(b=>b.id!==source).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>} {mode==="start"&&<input type="hidden" name="target_branch_id" value={source}/>}<label>Hedef grup<select name="target_group_id" required defaultValue=""><option value="" disabled>Grup seçiniz</option>{branchGroups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Gerçek START tarihi<input type="date" name="start_date" required/></label>{source&&!activePause&&<div className="warning">Bu tesis için aktif kapanış kaydı bulunamadı.</div>}</>}
   <button className="facilityPrimary" disabled={pending||(mode!=="close"&&!activePause)}>{pending?"İşlem yapılıyor…":mode==="close"?"Kapanışı Onayla":mode==="start"?"START Ver":"Aktar + START Ver"}</button>
  </form>{result&&<div className="result">{result}</div>}
  <div className="facilityInfo"><strong>Otomatik koruma:</strong> Kapanış anındaki kullanılan ve kalan ders sayısı sabitlenir. Kapalı dönemde hak tüketilmez. START işleminde kalan hak hedef grubun gerçek ders günlerine göre yeniden hesaplanır; Aktar + START aynı işlemi yeni havuz ve grup üzerinde tek adımda yapar.</div>
  <style jsx>{`.facilityOps{margin:18px 0 24px;border:1px solid #d8e6f7;border-radius:22px;background:#fff;box-shadow:0 14px 35px rgba(16,48,88,.08);overflow:hidden}.facilityOpsHead{display:flex;justify-content:space-between;gap:18px;padding:22px;background:linear-gradient(135deg,#082a58,#0d6bca);color:#fff}.facilityOpsHead span{font-size:10px;font-weight:950;letter-spacing:.13em;color:#91c9ff}.facilityOpsHead h2{font-size:20px;margin:6px 0}.facilityOpsHead p{max-width:720px;margin:0;color:#dcecff;font-size:12px;line-height:1.55}.facilityStatus{align-self:flex-start;white-space:nowrap;padding:8px 10px;border:1px solid rgba(255,255,255,.25);border-radius:999px;background:rgba(255,255,255,.12);font-size:10px;font-weight:900}.pauseList{display:grid;gap:8px;padding:14px 18px 0}.pauseCard{display:grid;gap:3px;padding:12px 14px;border:1px solid #ffd7d9;border-radius:13px;background:#fff7f7}.pauseCard b{font-size:10px;color:#b42e38}.pauseCard span{font-weight:900;color:#263b59}.pauseCard small{color:#6d7b8e}.facilityModes{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:16px 18px 0}.facilityModes button{min-height:45px;border:1px solid #d9e3ef;border-radius:12px;background:#f8fafd;color:#344765;font-weight:900}.facilityModes .active{border-color:#1769e8;background:#edf5ff;color:#1769e8}.facilityModes .danger{border-color:#dc5b62;background:#fff4f4;color:#b72f39}.facilityModes .start{border-color:#29976a;background:#f0fbf6;color:#19744e}.facilityForm{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:18px}.facilityForm label{font-size:12px;font-weight:850;color:#42536f}.facilityForm small{font-weight:600;color:#7b8798}.facilityForm select,.facilityForm input{display:block;width:100%;box-sizing:border-box;margin-top:7px;min-height:46px;padding:10px 12px;border:1px solid #d8e2ef;border-radius:12px;background:#fbfcff;color:#13233f;font:inherit}.wide{grid-column:span 2}.facilityPrimary{align-self:end;min-height:46px;border:0;border-radius:12px;background:#1769e8;color:#fff;font-weight:900}.facilityPrimary:disabled{opacity:.5}.warning,.result{padding:12px;border-radius:12px;font-size:12px}.warning{background:#fff6e8;color:#8a5a11}.result{margin:0 18px 14px;background:#eef8f3;color:#1d704d;font-weight:800}.facilityInfo{margin:0 18px 18px;padding:13px 14px;border:1px solid #d6e7fd;border-radius:13px;background:#f2f7ff;color:#53647d;font-size:12px;line-height:1.55}.facilityInfo strong{color:#17375f}@media(max-width:720px){.facilityOpsHead{flex-direction:column}.facilityModes,.facilityForm{grid-template-columns:1fr}.wide{grid-column:auto}.facilityOpsHead h2{font-size:18px}}`}</style>
 </section>;
}
