"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
type Item={id:string;student_id:string;lesson_date:string|null;status:string;note:string|null;student?:{first_name?:string;last_name?:string;student_number?:string|null}|null};
export default function CompensationManagementClient(){
 const [items,setItems]=useState<Item[]>([]),[tab,setTab]=useState<"planned"|"cancelled">("planned"),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[canDelete,setCanDelete]=useState(false),[message,setMessage]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/compensation-management",{cache:"no-store"});const j=await r.json();if(r.ok){setItems(j.items||[]);setCanDelete(Boolean(j.canDelete));}else setMessage(j.error||"Telafiler alınamadı.");setLoading(false)}
 useEffect(()=>{void load()},[]);
 const rows=useMemo(()=>items.filter(x=>x.status===tab),[items,tab]);
 async function cancel(item:Item){if(!confirm("Bu telafi iptal edilecek. Öğrenci bekleyen telafi listesinden çıkarılacak. Devam edilsin mi?"))return;setBusy(item.id);const r=await fetch("/api/compensation-management",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id})});const j=await r.json();setMessage(j.message||j.error||"İşlem tamamlandı.");setBusy(null);if(r.ok)await load()}
 async function remove(item:Item){if(!confirm("DİKKAT: Bu iptal edilmiş telafi kalıcı olarak silinecek. Bu işlem geri alınamaz. Devam edilsin mi?"))return;if(!confirm("Kalıcı silmeyi ikinci kez onaylıyor musunuz?"))return;setBusy(item.id);const r=await fetch("/api/compensation-management?id="+encodeURIComponent(item.id),{method:"DELETE"});const j=await r.json();setMessage(j.message||j.error||"İşlem tamamlandı.");setBusy(null);if(r.ok)await load()}
 return <main className="cmShell"><header><div><p>SPRİNTOS · DERS YÖNETİMİ</p><h1>Telafi Yönetimi</h1><span>Bekleyen telafileri iptal edin; iptal edilen kayıtları yetkiniz varsa kalıcı silebilirsiniz.</span></div><Link href="/ogrenciler">← Öğrenci Merkezine Dön</Link></header>
 {message?<div className="cmNotice">{message}<button onClick={()=>setMessage("")}>×</button></div>:null}
 <section className="cmStats"><button className={tab==="planned"?"active":""} onClick={()=>setTab("planned")}><span>Telafi Bekleyen</span><strong>{items.filter(x=>x.status==="planned").length}</strong></button><button className={tab==="cancelled"?"active danger":""} onClick={()=>setTab("cancelled")}><span>İptal Edilenler</span><strong>{items.filter(x=>x.status==="cancelled").length}</strong></button></section>
 <section className="cmList">{loading?<div className="empty">Telafiler yükleniyor…</div>:rows.length?rows.map(item=><article key={item.id}><div className="cmMain"><small>{item.student?.student_number||"Kursiyer"}</small><h3>{[item.student?.first_name,item.student?.last_name].filter(Boolean).join(" ")||"Öğrenci"}</h3><p><b>Telafi tarihi:</b> {item.lesson_date?new Date(item.lesson_date+"T12:00:00").toLocaleDateString("tr-TR"):"—"}</p>{item.note?<p className="note">{item.note}</p>:null}</div><div className="cmActions">{item.status==="planned"?<button disabled={busy===item.id} onClick={()=>void cancel(item)}>{busy===item.id?"İşleniyor…":"Telafiyi İptal Et"}</button>:<><span className="cancelled">İptal Edildi</span>{canDelete?<button className="delete" disabled={busy===item.id} onClick={()=>void remove(item)}>{busy===item.id?"Siliniyor…":"Kalıcı Sil"}</button>:null}</>}</div></article>):<div className="empty">Bu bölümde telafi kaydı bulunmuyor.</div>}</section>
 <style jsx>{`
 .cmShell{max-width:1100px;margin:0 auto;padding:24px;color:#10233f}.cmShell header{display:flex;justify-content:space-between;gap:18px;align-items:center;background:#fff;border:1px solid #dbe6f3;border-radius:20px;padding:22px}.cmShell header p{margin:0;color:#176fe8;font-size:11px;font-weight:900;letter-spacing:.1em}.cmShell h1{margin:5px 0;font-size:28px}.cmShell header span{color:#71839a;font-size:13px}.cmShell header a{color:#176fe8;font-weight:800;text-decoration:none;white-space:nowrap}.cmNotice{margin:14px 0;padding:12px 14px;background:#eef6ff;border:1px solid #bdd8fa;border-radius:12px;display:flex;justify-content:space-between}.cmNotice button{border:0;background:transparent;font-size:20px}.cmStats{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}.cmStats button{background:#fff;border:1px solid #dbe6f3;border-radius:16px;padding:16px;text-align:left;color:#60738d}.cmStats button strong{display:block;font-size:28px;color:#10233f;margin-top:6px}.cmStats button.active{border-color:#176fe8;box-shadow:0 0 0 2px rgba(23,111,232,.12)}.cmStats button.danger{border-color:#ef9a9a}.cmList{display:grid;gap:10px}.cmList article{display:flex;justify-content:space-between;gap:16px;align-items:center;background:#fff;border:1px solid #dbe6f3;border-radius:16px;padding:16px}.cmMain small{color:#71839a}.cmMain h3{margin:4px 0 8px}.cmMain p{margin:3px 0;font-size:13px}.note{color:#71839a}.cmActions{display:flex;gap:8px;align-items:center}.cmActions button{border:1px solid #efb2b2;background:#fff5f5;color:#b42318;border-radius:10px;padding:10px 12px;font-weight:800}.cmActions .delete{background:#b42318;color:#fff;border-color:#b42318}.cancelled{padding:7px 10px;border-radius:999px;background:#f1f5f9;color:#64748b;font-size:12px;font-weight:800}.empty{padding:36px;text-align:center;background:#fff;border:1px dashed #cbd5e1;border-radius:16px;color:#71839a}@media(max-width:700px){.cmShell{padding:12px}.cmShell header{align-items:flex-start;flex-direction:column;padding:16px}.cmShell h1{font-size:23px}.cmStats{gap:8px}.cmStats button{padding:13px}.cmList article{align-items:flex-start;flex-direction:column}.cmActions{width:100%}.cmActions button{flex:1}.cmActions .cancelled{flex:1;text-align:center}}`}</style>
 </main>
}