import Link from "next/link";
import { requireProfile } from "@/lib/auth/profile";
import { createClient } from "@/lib/supabase/server";
import { SPRINT_MESSAGE_TEMPLATE_MAP } from "@/lib/messaging/sprint-message-catalog";
import PaymentActions from "./payment-actions";
import SecurePaymentLink from "./secure-payment-link";

export const dynamic = "force-dynamic";
type SearchParams = Promise<Record<string,string|string[]|undefined>>;
type PhoneCandidate={phone:string;label:string;source:string};
function normalizeText(v:unknown){return String(v||"").trim().toLocaleLowerCase("tr-TR")}
function isAdultCourse(v:unknown){const t=normalizeText(v);return t.includes("yetişkin")||t.includes("yetiskin")||t.includes("adult")||t.includes("master")}
function phoneKey(v:unknown){let d=String(v||"").replace(/\D/g,"");if(!d)return"";if(d.startsWith("0090"))d=d.slice(2);if(d.startsWith("90")&&d.length===12)return d;if(d.startsWith("0")&&d.length===11)return`90${d.slice(1)}`;if(d.length===10)return`90${d}`;return d}
function addCandidate(list:PhoneCandidate[],phone:unknown,label:string,source:string){const n=phoneKey(phone);if(!n||n.length<10||list.some(i=>phoneKey(i.phone)===n))return;list.push({phone:String(phone),label,source})}

export default async function PaymentInformationPage({searchParams}:{searchParams:SearchParams}){
 const params=await searchParams;const studentId=typeof params.studentId==="string"?params.studentId:"";
 const profile=await requireProfile(["owner","admin","branch_manager","registration_staff","accounting"]);const organizationId=profile.organization_id;
 const template=SPRINT_MESSAGE_TEMPLATE_MAP.bank_info;const message=template?.body||"Ödeme bilgisi şablonu bulunamadı.";
 let studentName="";let phoneCandidates:PhoneCandidate[]=[];let lastSentAt="";
 if(organizationId&&studentId){const supabase=await createClient();const[{data:student},{data:latestMessage}]=await Promise.all([
  supabase.from("students").select("id,first_name,last_name,birth_date,phone,guardian_name,guardian_phone,preferred_group_id").eq("organization_id",organizationId).eq("id",studentId).maybeSingle(),
  supabase.from("message_logs").select("sent_at,prepared_at,status").eq("organization_id",organizationId).eq("student_id",studentId).eq("template_key","bank_info").eq("status","sent").order("sent_at",{ascending:false,nullsFirst:false}).limit(1).maybeSingle()]);
  lastSentAt=latestMessage?.sent_at||latestMessage?.prepared_at||"";
  if(student){studentName=`${student.first_name||""} ${student.last_name||""}`.trim();let courseType="";if(student.preferred_group_id){const{data:group}=await supabase.from("training_groups").select("course_type").eq("organization_id",organizationId).eq("id",student.preferred_group_id).maybeSingle();courseType=group?.course_type||""}const adult=isAdultCourse(courseType);if(adult){addCandidate(phoneCandidates,student.phone,"Kursiyer telefonu","Öğrenci kaydı");addCandidate(phoneCandidates,student.guardian_phone,student.guardian_name?`${student.guardian_name} · veli`:"Veli telefonu","Öğrenci kaydı")}else{addCandidate(phoneCandidates,student.guardian_phone,student.guardian_name?`${student.guardian_name} · veli`:"Veli telefonu","Öğrenci kaydı");addCandidate(phoneCandidates,student.phone,"Kursiyer telefonu","Öğrenci kaydı")}
   const[{data:guardianLinks},{data:preRegistrations}]=await Promise.all([supabase.from("guardian_students").select("guardian_id,is_primary,is_payment_contact,receives_messages").eq("student_id",studentId).order("is_payment_contact",{ascending:false}).order("is_primary",{ascending:false}),supabase.from("pre_registrations").select("guardian_full_name,phone,whatsapp_phone").eq("organization_id",organizationId).eq("converted_student_id",studentId).order("created_at",{ascending:false}).limit(5)]);
   const guardianIds=(guardianLinks||[]).map((l:any)=>l.guardian_id).filter(Boolean);if(guardianIds.length){const{data:guardians}=await supabase.from("guardians").select("id,full_name,phone,is_active").eq("organization_id",organizationId).in("id",guardianIds);const gm=new Map((guardians||[]).map((g:any)=>[g.id,g]));for(const link of guardianLinks||[]){const g:any=gm.get((link as any).guardian_id);if(!g||g.is_active===false)continue;const role=(link as any).is_payment_contact?"ödeme yetkilisi":(link as any).is_primary?"birincil veli":"bağlı veli";addCandidate(phoneCandidates,g.phone,`${g.full_name||"Veli"} · ${role}`,"Veli merkezi")}}
   for(const pre of preRegistrations||[]){const name=(pre as any).guardian_full_name||"Ön kayıt iletişimi";addCandidate(phoneCandidates,(pre as any).whatsapp_phone,`${name} · WhatsApp`,"Ön kayıt");addCandidate(phoneCandidates,(pre as any).phone,`${name} · telefon`,"Ön kayıt")}
  }
 }
 return <main style={{maxWidth:900,margin:"0 auto",padding:"28px 16px 110px"}}><section style={{background:"#fff",border:"1px solid #dbe6f0",borderRadius:22,overflow:"hidden",boxShadow:"0 16px 42px rgba(8,45,82,.10)"}}><header style={{padding:24,background:"linear-gradient(135deg,#082a4b,#0b5f9d)",color:"white"}}><div style={{fontSize:11,fontWeight:900,letterSpacing:".12em",color:"#9ed4ff"}}>SPRİNT YÜZME OKULU · ÖDEME MERKEZİ</div><h1 style={{margin:"7px 0 5px"}}>Ödeme Bilgileri</h1><p style={{margin:0,color:"#dceeff"}}>{studentName?`${studentName} · `:""}Güvenli IBAN / Havale ödeme akışı</p></header><div style={{padding:22}}>
 <nav style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:6,padding:7,borderRadius:15,background:"#eef4f9",marginBottom:18}}><span style={{padding:"11px 8px",borderRadius:11,background:"#fff",color:"#0a5da8",fontWeight:900,textAlign:"center"}}>Güvenli Ödeme</span>{studentId?<Link href={`/ogrenciler/${studentId}?payment=history`} style={{padding:"11px 8px",color:"#244b6f",fontWeight:800,textAlign:"center",textDecoration:"none"}}>Ödeme Kaydı</Link>:<span style={{padding:"11px 8px",color:"#8295a7",fontWeight:800,textAlign:"center"}}>Ödeme Kaydı</span>}<Link href="/hazir-mesajlar" style={{padding:"11px 8px",color:"#244b6f",fontWeight:800,textAlign:"center",textDecoration:"none"}}>Hazır Mesajlar</Link></nav>
 {studentId?<SecurePaymentLink studentId={studentId} studentName={studentName} phoneCandidates={phoneCandidates}/>:<div style={{padding:18,border:"1px solid #efcf9b",borderRadius:16,background:"#fff9ef",color:"#7a5312"}}><b>Önce kursiyer seçiniz.</b><div style={{marginTop:5,fontSize:12}}>Güvenli ödeme bağlantısı kursiyerin dijital dosyasından açıldığında otomatik hazırlanır.</div></div>}
 <details style={{marginTop:18}}><summary style={{cursor:"pointer",fontSize:12,fontWeight:900,color:"#315f86"}}>Yetkili personel için manuel IBAN / QR araçları</summary><div style={{marginTop:12,padding:16,border:"1px solid #d9e5ef",borderRadius:16,background:"#fbfdff"}}><div style={{fontSize:11,fontWeight:900,color:"#71869a"}}>VAKIFBANK · MANUEL İŞLEM</div><div style={{marginTop:7,fontSize:17,fontWeight:900,color:"#123a5d"}}>TR14 0001 5001 5800 7357 4815 06</div><PaymentActions message={message} qrUrl="/payment/vakifbank-qr.jpg" studentId={studentId} phoneCandidates={phoneCandidates} studentName={studentName} initialLastSentAt={lastSentAt}/></div></details>
 {studentId?<div style={{marginTop:18,paddingTop:16,borderTop:"1px solid #e5edf4"}}><Link href={`/ogrenciler/${studentId}`} style={{display:"inline-flex",padding:"11px 14px",borderRadius:12,color:"#0c3159",fontWeight:800,textDecoration:"none",border:"1px solid #d6e3ee",fontSize:12}}>Kursiyer Dosyasına Dön</Link></div>:null}
 </div></section></main>
}
