import { requireProfile } from "@/lib/auth/profile";
import { formatDate, getGuardianContext, weekdayLabel } from "@/lib/guardian/data";
import { EmptyGuardian, GuardianHeader, StatusPill } from "@/app/veli-paneli/guardian-ui";
import "@/app/veli-paneli/veli.css";
export const dynamic = "force-dynamic";
export default async function Page({ searchParams }:{searchParams:Promise<{child?:string}>}){
 const profile=await requireProfile(["guardian"]); const {child}=await searchParams; const data=await getGuardianContext(profile.id,child);
 return <main className="guardianShell"><GuardianHeader name={profile.full_name||"Değerli Velimiz"} students={data.students} selectedId={data.selected?.id}/><div className="guardianContent"><h1 className="guardianSectionTitle">Dersler ve Yoklama</h1><p className="guardianSectionLead">Planlanan ders günleri, katılım geçmişi ve eğitmen notları.</p>{!data.selected?<EmptyGuardian title="Öğrenci bulunamadı" text="Öğrenci bağlantısı tamamlandığında ders kayıtları burada görünecek."/>:<><section className="guardianCard"><div className="guardianCardHeader"><h2>Haftalık Program</h2></div><div className="scheduleChips">{data.schedules.length?data.schedules.map((s:any)=><span className="scheduleChip" key={s.id}>{weekdayLabel(Number(s.weekday))} · {String(s.start_time).slice(0,5)}–{String(s.end_time).slice(0,5)}</span>):<span>Program henüz tanımlanmadı.</span>}</div></section><section className="guardianCard" style={{marginTop:18}}><div className="guardianCardHeader"><h2>Yoklama Geçmişi</h2></div><table className="guardianTable"><thead><tr><th>Tarih</th><th>Durum</th><th>Eğitmen Notu</th></tr></thead><tbody>{data.attendance.map((a:any)=><tr key={a.id}><td>{formatDate(a.lesson_date)}</td><td><StatusPill tone={a.status==='present'?'green':a.status==='excused'?'orange':'red'}>{a.status==='present'?'Katıldı':a.status==='excused'?'Mazeretli':'Katılmadı'}</StatusPill></td><td>{a.coach_note||'—'}</td></tr>)}</tbody></table>{!data.attendance.length?<p className="guardianSectionLead">Henüz yoklama kaydı bulunmuyor.</p>:null}</section></>}</div></main>
}
