import Link from "next/link";
import { createClient as createAdminClient } from "@supabase/supabase-js";
import UstGezinme from "@/app/components/UstGezinme";
import { requireProfile } from "@/lib/auth/profile";
import { createClient } from "@/lib/supabase/server";
import PendingSubmitButton from "@/app/ogrenciler/[id]/pending-submit-button";
import { createGuardianRequest, manageGuardianRequest } from "@/app/veliler/actions";
import "@/app/veliler/guardian-management.css";
import "@/app/veli-paneli/veli.css";

export const dynamic="force-dynamic";
const statusLabels:Record<string,string>={new:"Yeni",reviewing:"İnceleniyor",approval_pending:"Yönetici Onayı",answered:"Yanıtlandı",resolved:"Çözüldü",rejected:"Reddedildi",archived:"Arşivlendi"};
const categoryLabels:Record<string,string>={group_schedule:"Grup / Saat",branch:"Şube Değişikliği",lesson:"Ders / Telafi",payment:"Ödeme / Vade",coach:"Eğitmen Görüşü",health:"Sağlık / Özel Durum",document:"Belge Talebi",feedback:"Öneri / Memnuniyet",complaint:"Şikâyet",other:"Diğer"};
function adminClient(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error("Supabase bağlantısı yok.");return createAdminClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}})}
function fmt(v:string){return new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date(v))}

export default async function GuardianRequestsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const profile=await requireProfile(["owner","admin","branch_manager","registration_staff","accounting","coach","guardian"]);const query=await searchParams;const guardian=profile.role==="guardian";
 const db=guardian?await createClient():adminClient();const org=profile.organization_id!;
 const requestQuery=db.from("guardian_requests").select("*").eq("organization_id",org).order("created_at",{ascending:false}).limit(200);
 if(guardian)requestQuery.eq("guardian_id",profile.id);else if(query.guardian)requestQuery.eq("guardian_id",query.guardian);
 const [requestsRes,linksRes,studentsRes,guardiansRes,staffRes]=await Promise.all([
  requestQuery,
  guardian?db.from("guardian_students").select("student_id").eq("guardian_id",profile.id):Promise.resolve({data:[]}),
  db.from("students").select("id,first_name,last_name,student_number,branch_id").eq("organization_id",org).limit(5000),
  guardian?Promise.resolve({data:[]}):db.from("profiles").select("id,full_name,phone").eq("organization_id",org).eq("role","guardian"),
  guardian?Promise.resolve({data:[]}):db.from("profiles").select("id,full_name,role").eq("organization_id",org).eq("is_active",true).in("role",["owner","admin","branch_manager","registration_staff","accounting","coach"]),
 ]);
 const requests=requestsRes.data||[],students=studentsRes.data||[];const studentMap=new Map(students.map((s:any)=>[s.id,s]));const guardianMap=new Map((guardiansRes.data||[]).map((g:any)=>[g.id,g]));const linked=new Set((linksRes.data||[]).map((l:any)=>l.student_id));const visibleStudents=guardian?students.filter((s:any)=>linked.has(s.id)):students;
 const shell=<main className="guardianAdminPage"><div className="guardianAdminWrap"><header className="guardianHero"><div><small>SPRİNTOS · TALEP VE GÖRÜŞ</small><h1>{guardian?"Talep ve Görüşlerim":"Veli Talep Merkezi"}</h1><p>{guardian?"Sorunuzu veya talebinizi yönetime güvenli biçimde iletin.":"Veli taleplerini görevlendirin, cevaplayın ve sonuçlandırın."}</p></div><div className="guardianHeroActions"><Link href={guardian?"/veli-paneli":"/veliler"}>Geri Dön</Link></div></header>{query.saved?<div className="guardianNotice">{query.saved}</div>:null}{query.error?<div className="guardianNotice error">{query.error}</div>:null}{requestsRes.error?<div className="guardianNotice error">Talep veri tabanı henüz kurulmadı. 015 numaralı SQL dosyası uygulanmalıdır.</div>:null}
 {guardian?<section className="guardianPanel"><div className="guardianEyebrow">YENİ TALEP</div><h2>Yönetime mesaj gönder</h2><form action={createGuardianRequest} className="guardianForm"><label>İlgili öğrenci<select name="student_id" required><option value="">Öğrenci seçiniz</option>{visibleStudents.map((s:any)=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</select></label><label>Kategori<select name="category">{Object.entries(categoryLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Öncelik<select name="priority"><option value="normal">Normal</option><option value="high">Önemli</option><option value="urgent">Acil</option><option value="low">Düşük</option></select></label><label>Konu<input name="subject" required maxLength={200}/></label><label>Açıklama<textarea name="description" rows={5} required/></label><PendingSubmitButton className="guardianButton primary" pendingText="Talebiniz gönderiliyor…">Talebi Yönetime Gönder</PendingSubmitButton></form></section>:null}
 <section className="guardianRequestList" style={{marginTop:16}}>{requests.map((r:any)=>{const s:any=studentMap.get(r.student_id);const g:any=guardianMap.get(r.guardian_id);return <article className={`guardianRequest ${r.priority}`} id={`talep-${r.id}`} key={r.id}><div className="guardianRequestHead"><div><small>{r.request_number} · {categoryLabels[r.category]||r.category}</small><h3>{r.subject}</h3></div><span className="guardianPill">{statusLabels[r.status]||r.status}</span></div><div className="guardianRequestMeta"><span>{s?`${s.first_name} ${s.last_name}`:"Genel talep"}</span>{g?<span>{g.full_name||g.phone}</span>:null}<span>{fmt(r.created_at)}</span><span>Öncelik: {r.priority}</span></div><p>{r.description}</p>{r.guardian_response?<div className="guardianResponse"><b>Yönetimin cevabı</b><p>{r.guardian_response}</p></div>:null}{!guardian&&r.internal_note?<div className="guardianInternal"><b>Kurum içi not</b><p>{r.internal_note}</p></div>:null}{!guardian?<form action={manageGuardianRequest} className="guardianForm"><input type="hidden" name="request_id" value={r.id}/><label>Durum<select name="status" defaultValue={r.status}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Öncelik<select name="priority" defaultValue={r.priority}><option value="low">Düşük</option><option value="normal">Normal</option><option value="high">Önemli</option><option value="urgent">Acil</option></select></label><label>Atanan personel<select name="assigned_to" defaultValue={r.assigned_to||""}><option value="">Atama yok</option>{(staffRes.data||[]).map((p:any)=><option key={p.id} value={p.id}>{p.full_name} · {p.role}</option>)}</select></label><label>Kurum içi not<textarea name="internal_note" rows={3} defaultValue={r.internal_note||""}/></label><label>Veliye gönderilecek cevap<textarea name="guardian_response" rows={4} defaultValue={r.guardian_response||""}/></label><div className="guardianFormActions"><PendingSubmitButton className="guardianButton primary" pendingText="Talep güncelleniyor…">Talebi Güncelle</PendingSubmitButton></div></form>:null}</article>})}{!requests.length&&!requestsRes.error?<div className="guardianEmpty">Henüz talep bulunmuyor.</div>:null}</section></div></main>;
 return guardian?shell:<><UstGezinme/>{shell}</>;
}
