import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient as createAdminClient } from "@supabase/supabase-js";
import UstGezinme from "@/app/components/UstGezinme";
import PendingSubmitButton from "@/app/ogrenciler/[id]/pending-submit-button";
import { requireProfile } from "@/lib/auth/profile";
import { linkGuardianStudent, unlinkGuardianStudent, updateGuardian } from "../actions";
import StudentSearchSelect from "./student-search-select";
import "../guardian-management.css";

export const dynamic="force-dynamic";
function adminClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase bağlantısı yok.");return createAdminClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function date(v?:string|null){return v?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date(v)):"—"}

export default async function GuardianFile({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const profile=await requireProfile(["owner","admin","branch_manager","registration_staff"]);const{id}=await params;const query=await searchParams;const admin=adminClient();const org=profile.organization_id!;
 const [guardianRes,linksRes,studentsRes,requestsRes]=await Promise.all([
  admin.from("profiles").select("id,full_name,phone,email,is_active,last_sign_in_at,created_at").eq("organization_id",org).eq("role","guardian").eq("id",id).maybeSingle(),
  admin.from("guardian_students").select("guardian_id,student_id,relationship,is_primary,is_payment_contact,receives_messages,portal_access,is_emergency_contact,created_at").eq("guardian_id",id),
  admin.from("students").select("id,first_name,last_name,student_number,status,guardian_name,guardian_phone").eq("organization_id",org).eq("is_deleted",false).order("first_name"),
  admin.from("guardian_requests").select("id,request_number,category,subject,status,priority,created_at,updated_at").eq("organization_id",org).eq("guardian_id",id).order("created_at",{ascending:false}).limit(30),
 ]);
 const guardian=guardianRes.data;if(!guardian)notFound();const links=linksRes.data||[];const students=studentsRes.data||[];const studentMap=new Map(students.map((s:any)=>[s.id,s]));const linkedIds=new Set(links.map((l:any)=>l.student_id));
 return <><UstGezinme/><main className="guardianAdminPage"><div className="guardianAdminWrap">
  <header className="guardianHero"><div><small>SPRİNTOS · DİJİTAL VELİ DOSYASI</small><h1>{guardian.full_name||"Veli Hesabı"}</h1><p>{guardian.phone||"Telefon yok"} · Son giriş: {date(guardian.last_sign_in_at)}</p></div><div className="guardianHeroActions"><Link href="/veliler">Velilere Dön</Link><Link className="primary" href={`/veli-talepleri?guardian=${id}`}>Talepleri Aç</Link></div></header>
  {query.saved?<div className="guardianNotice">{query.saved}</div>:null}{query.error?<div className="guardianNotice error">{query.error}</div>:null}
  <div className="guardianDetailGrid"><section className="guardianPanel"><div className="guardianEyebrow">HESAP VE GÜVENLİK</div><h2>Veli bilgileri</h2><form action={updateGuardian} className="guardianForm"><input type="hidden" name="guardian_id" value={id}/><label>Ad Soyad<input name="full_name" defaultValue={guardian.full_name||""} required/></label><label>Telefon<input name="phone" defaultValue={guardian.phone||""}/></label><div className="guardianChecks"><label><input type="checkbox" name="is_active" defaultChecked={guardian.is_active}/> Portal hesabı aktif</label></div><PendingSubmitButton className="guardianButton primary" pendingText="Bilgiler kaydediliyor…">Bilgileri Kaydet</PendingSubmitButton></form><div className="guardianChild" style={{marginTop:14}}><span><b>Oluşturulma</b><small>{date(guardian.created_at)}</small></span><span><b>Son giriş</b><small>{date(guardian.last_sign_in_at)}</small></span></div></section>
  <section className="guardianPanel"><div className="guardianEyebrow">ÖĞRENCİ BAĞLANTILARI</div><h2>Bağlı öğrenciler</h2><div className="guardianChildren">{links.map((l:any)=>{const s:any=studentMap.get(l.student_id);return <div className="guardianChild" key={l.student_id}><span><b>{s?`${s.first_name} ${s.last_name}`:"Öğrenci"}</b><small>{s?.student_number||"Numara yok"} · {l.relationship||"Veli"}</small></span><span><Link href={`/ogrenciler/${l.student_id}`}>Dosyayı Aç</Link>{["owner","admin"].includes(profile.role)?<form action={unlinkGuardianStudent}><input type="hidden" name="guardian_id" value={id}/><input type="hidden" name="student_id" value={l.student_id}/><button className="deleteNoteButton">Bağı Kaldır</button></form>:null}</span></div>})}</div><form action={linkGuardianStudent} className="guardianForm" style={{marginTop:18}}><input type="hidden" name="guardian_id" value={id}/><StudentSearchSelect students={students.filter((s:any)=>!linkedIds.has(s.id)).map((s:any)=>({id:s.id,name:`${s.first_name||""} ${s.last_name||""}`.trim(),number:s.student_number||""}))}/><label>Yakınlık<select name="relationship"><option>Anne</option><option>Baba</option><option>Yasal Vasi</option><option>Acil Durum Kişisi</option><option>Diğer</option></select></label><div className="guardianChecks"><label><input type="checkbox" name="is_primary"/> Birincil veli</label><label><input type="checkbox" name="is_payment_contact"/> Ödeme sorumlusu</label><label><input type="checkbox" name="receives_messages" defaultChecked/> Mesajları alsın</label><label><input type="checkbox" name="portal_access" defaultChecked/> Portal erişimi</label><label><input type="checkbox" name="is_emergency_contact"/> Acil durumda ara</label></div><PendingSubmitButton className="guardianButton primary" pendingText="Bağlantı kaydediliyor…">Öğrenciyi Bağla</PendingSubmitButton></form></section></div>
  <section className="guardianPanel" style={{marginTop:16}}><div className="guardianCardHead"><div><div className="guardianEyebrow">TALEP VE GÖRÜŞ GEÇMİŞİ</div><h2>Veli talepleri</h2></div><Link className="guardianButton" href={`/veli-talepleri?guardian=${id}`}>Tümünü Yönet</Link></div><div className="guardianRequestList">{(requestsRes.data||[]).map((r:any)=><article className={`guardianRequest ${r.priority}`} key={r.id}><div className="guardianRequestHead"><div><small>{r.request_number}</small><h3>{r.subject}</h3></div><span className="guardianPill">{r.status}</span></div><div className="guardianRequestMeta"><span>{r.category}</span><span>{r.priority}</span><span>{date(r.created_at)}</span></div></article>)}{requestsRes.error?<div className="guardianNotice error">Talep modülü için 015 SQL kurulumu gereklidir.</div>:null}{!requestsRes.data?.length&&!requestsRes.error?<div className="guardianEmpty">Henüz veli talebi bulunmuyor.</div>:null}</div></section>
 </div></main></>;
}
