import Link from "next/link";
import { requireProfile } from "@/lib/auth/profile";
import { createClient } from "@/lib/supabase/server";
import AttendanceExcelButton from "../attendance-excel-button";
import "../history.css";
import "../history-polish.css";
export const dynamic="force-dynamic";
const tr=(v:string)=>new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${v}T12:00:00`));
const statusLabel=(status?:string|null)=>status==="present"?"Katıldı":status==="absent"?"Katılmadı":status==="excused"?"İzinli":status==="compensation"?"Telafi":"Belirsiz";
export default async function Page(){const profile=await requireProfile(["owner","admin","branch_manager","registration_staff","accounting","coach"]);const s=await createClient();const [{data:rows},{data:students},{data:groups},{data:branches}]=await Promise.all([s.from("attendance_records").select("student_id,group_id,branch_id,lesson_date,status").eq("organization_id",profile.organization_id).order("lesson_date",{ascending:false}).limit(1000),s.from("students").select("id,first_name,last_name").eq("organization_id",profile.organization_id),s.from("training_groups").select("id,name").eq("organization_id",profile.organization_id),s.from("branches").select("id,name,short_name").eq("organization_id",profile.organization_id)]);const sm=new Map((students||[]).map(x=>[x.id,`${x.first_name||""} ${x.last_name||""}`.trim()]));const gm=new Map((groups||[]).map(x=>[x.id,x.name]));const bm=new Map((branches||[]).map(x=>[x.id,x.short_name||x.name]));const dates=new Map<string,any[]>();for(const r of rows||[]){const a=dates.get(r.lesson_date)||[];a.push(r);dates.set(r.lesson_date,a)}const exportRows=(rows||[]).map((r:any)=>({date:tr(r.lesson_date),student:sm.get(r.student_id)||"Kursiyer",branch:bm.get(r.branch_id)||"Şube",group:gm.get(r.group_id)||"Grup",status:statusLabel(r.status)}));return <main className="ahRoot"><header className="ahHead"><div><small>SPRINTOS · YOKLAMA</small><h1>Yoklama Geçmişi</h1><p>En yeni derslerden başlayarak geçmiş yoklamaları hızlıca inceleyin.</p></div><div className="ahHeadActions"><AttendanceExcelButton rows={exportRows} fileName="sprintos-yoklama-gecmisi"/><Link href="/yoklama">Günlük Yoklama</Link></div></header><nav className="ahTabs" aria-label="Yoklama görünümü"><Link href="/yoklama">Günlük Yoklama</Link><Link href="/yoklama/aylik">Tüm Ay</Link><Link className="active" href="/yoklama/gecmis">Geçmiş</Link></nav><div className="ahPeriodHint">Son {rows?.length||0} kayıt · tarih sırasına göre en yeniden eskiye</div><div className="ahDays">{[...dates.entries()].map(([date,list])=><section className="ahDay" key={date}><header><strong>{tr(date)}</strong><span>{list.length} kayıt</span></header>{list.map((r,i)=><div className="ahRow" key={`${r.student_id}-${i}`}><div><b>{sm.get(r.student_id)||"Kursiyer"}</b><small>{bm.get(r.branch_id)||"Şube"} · {gm.get(r.group_id)||"Grup"}</small></div><span className={`st ${r.status}`}>{r.status==="present"?"✓ Geldi":r.status==="absent"?"✕ Katılmadı":r.status==="excused"?"○ İzinli":"T Telafi"}</span></div>)}</section>)}{!dates.size&&<div className="ahEmpty">Henüz geçmiş yoklama kaydı bulunamadı.</div>}</div></main>}
