import Link from "next/link";
import { createClient as createAdminClient } from "@supabase/supabase-js";
import UstGezinme from "@/app/components/UstGezinme";
import { requireProfile } from "@/lib/auth/profile";
import GuardianIcon from "./guardian-icon";
import DeleteGuardianButton from "./delete-guardian-button";
import UnlinkStudentButton from "./unlink-student-button";
import GuardianPortalActions from "./guardian-portal-actions";
import "./guardian-management.css";

export const dynamic = "force-dynamic";
function adminClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase yönetici bağlantısı yapılandırılmamış.");return createAdminClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function norm(v:unknown){return String(v||"").trim().toLocaleLowerCase("tr-TR")}

export default async function GuardianManagementPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const profile=await requireProfile(["owner","admin","branch_manager","registration_staff"]);const query=await searchParams;const organizationId=profile.organization_id!;const admin=adminClient();
 const [profilesRes,guardianRecordsRes,linksRes,studentsRes,enrollmentsRes,groupsRes,branchesRes,requestsRes]=await Promise.all([
  admin.from("profiles").select("id,full_name,phone,email,is_active,last_sign_in_at,created_at").eq("organization_id",organizationId).eq("role","guardian").order("full_name"),
  admin.from("guardians").select("id,auth_user_id,full_name,phone,email,relationship,login_enabled,is_active,last_login_at").eq("organization_id",organizationId),
  admin.from("guardian_students").select("guardian_id,student_id,relationship,is_primary,portal_access").limit(5000),
  admin.from("students").select("id,first_name,last_name,phone,status,branch_id,preferred_group_id,guardian_name,guardian_phone").eq("organization_id",organizationId).eq("is_deleted",false).limit(5000),
  admin.from("student_enrollments").select("student_id,group_id,status,created_at").eq("organization_id",organizationId).eq("status","active").order("created_at",{ascending:false}),
  admin.from("training_groups").select("id,name,branch_id").eq("organization_id",organizationId),
  admin.from("branches").select("id,name").eq("organization_id",organizationId),
  admin.from("guardian_requests").select("id,status,priority").eq("organization_id",organizationId).limit(1000),
 ]);
 const guardians=profilesRes.data||[],guardianRecords=guardianRecordsRes.data||[],rawLinks=linksRes.data||[],students=studentsRes.data||[],requests=requestsRes.data||[];
 const activeStudentIds=new Set(students.filter((s:any)=>String(s.status||"").toLowerCase()==="active").map((s:any)=>s.id));
 const guardianRecordByAuth=new Map(guardianRecords.filter((g:any)=>g.auth_user_id).map((g:any)=>[g.auth_user_id,g]));
 const guardianRecordIds=new Set(guardianRecords.map((g:any)=>g.id));
 const allLinks=rawLinks.filter((l:any)=>guardianRecordIds.has(l.guardian_id));
 const links=allLinks.filter((l:any)=>activeStudentIds.has(l.student_id));
 const studentMap=new Map(students.map((s:any)=>[s.id,s]));const groupMap=new Map((groupsRes.data||[]).map((g:any)=>[g.id,g]));const branchMap=new Map((branchesRes.data||[]).map((b:any)=>[b.id,b]));const enrollmentMap=new Map<string,any>();for(const e of enrollmentsRes.data||[])if(!enrollmentMap.has(e.student_id))enrollmentMap.set(e.student_id,e);
 const q=norm(query.q),status=query.status||"all",linkFilter=query.link||"all",branchFilter=query.branch||"",groupFilter=query.group||"";
 const hydrated=guardians.map((g:any)=>{const guardianRecord:any=guardianRecordByAuth.get(g.id);const guardianLinks=guardianRecord?links.filter((l:any)=>l.guardian_id===guardianRecord.id):[];const everyLink=guardianRecord?allLinks.filter((l:any)=>l.guardian_id===guardianRecord.id):[];const onlyPassive=everyLink.length>0&&guardianLinks.length===0;const portalEnabled=g.is_active!==false&&guardianRecord?.is_active!==false&&guardianRecord?.login_enabled!==false;return{...g,portalEnabled,guardianRecord,links:guardianLinks,allLinks:everyLink,onlyPassive,needsRepair:!guardianRecord||(everyLink.length===0)}});
 const rows=hydrated.filter((g:any)=>{if(g.onlyPassive)return false;if(status==="active"&&(!g.portalEnabled||!g.last_sign_in_at))return false;if(status==="inactive"&&g.portalEnabled)return false;if(status==="pending"&&(!g.portalEnabled||g.last_sign_in_at))return false;if(status==="unlinked"&&g.links.length)return false;if(status==="repair"&&!g.needsRepair)return false;if(linkFilter==="multiple"&&g.links.length<2)return false;if(linkFilter==="single"&&g.links.length!==1)return false;
 if((branchFilter||groupFilter)&&!g.links.some((l:any)=>{const s:any=studentMap.get(l.student_id),e:any=enrollmentMap.get(l.student_id),gr:any=groupMap.get(e?.group_id||s?.preferred_group_id);return(!branchFilter||(gr?.branch_id||s?.branch_id)===branchFilter)&&(!groupFilter||gr?.id===groupFilter)}))return false;
 if(!q)return true;const childNames=g.links.map((l:any)=>{const s:any=studentMap.get(l.student_id);return `${s?.first_name||""} ${s?.last_name||""}`}).join(" ");return norm(`${g.full_name} ${g.phone} ${g.email} ${childNames}`).includes(q)});
 const linkedIds=new Set(links.map((l:any)=>l.student_id));const unlinkedStudents=students.filter((s:any)=>activeStudentIds.has(s.id)&&!linkedIds.has(s.id)&&(s.guardian_phone||s.phone));const schemaError=requestsRes.error?.message||null;const dataError=[profilesRes,guardianRecordsRes,linksRes,studentsRes,enrollmentsRes,groupsRes,branchesRes].some(r=>r.error);const visibleGuardians=hydrated.filter((g:any)=>!g.onlyPassive);const pendingCount=visibleGuardians.filter((g:any)=>g.portalEnabled&&!g.last_sign_in_at).length;const repairCount=visibleGuardians.filter((g:any)=>g.needsRepair).length;const canDelete=["owner","admin"].includes(profile.role);
 return <><UstGezinme/><main className="guardianAdminPage"><div className="guardianAdminWrap"><header className="guardianHero"><div><small>SPRİNTOS · VELİ İLİŞKİLERİ</small><h1>Veli Yönetim Merkezi</h1><p>Portal hesabı, öğrenci bağlantısı, şifre ve WhatsApp gönderimi artık tek merkezde yönetilir.</p></div><div className="guardianHeroActions"><Link href="/veli-talepleri"><GuardianIcon name="message"/>Talep ve Görüşler</Link><Link href="/veliler/icerik"><GuardianIcon name="file"/>Portal İçerikleri</Link><Link className="primary" href="/veliler/ogrenciden-olustur"><GuardianIcon name="users"/>Toplu İşlemler</Link></div></header>
 {dataError?<div role="alert" className="guardianNotice error">Veli veya öğrenci bilgileri tam yüklenemedi. Bağlantıları değiştirmeden önce sayfayı yenileyin.</div>:null}{query.saved?<div className="guardianNotice">{query.saved}</div>:null}{query.error?<div className="guardianNotice error">{query.error}</div>:null}{schemaError?<div className="guardianNotice error">Talep tablosu henüz kurulmadı. 015 numaralı SQL kurulumu uygulanmalıdır.</div>:null}
 <section className="guardianStats"><article className="guardianStat"><span>Toplam Portal Hesabı</span><strong>{visibleGuardians.length}</strong></article><Link className="guardianStat guardianStatLink" href="/veliler?status=active"><span>Aktif Portal</span><strong>{visibleGuardians.filter((g:any)=>g.portalEnabled&&g.last_sign_in_at).length}</strong></Link><Link className="guardianStat guardianStatLink" href="/veliler?status=pending"><span>İlk Giriş Bekleniyor</span><strong>{pendingCount}</strong></Link><article className="guardianStat"><span>Bağlı Öğrenci</span><strong>{linkedIds.size}</strong></article><Link className="guardianStat guardianStatLink" href="/veliler/ogrenciden-olustur"><span>Bağlantı Bekleyen</span><strong>{unlinkedStudents.length}</strong></Link><Link className="guardianStat guardianStatLink guardianRepairStat" href="/veliler?status=repair"><span>Onarım Gerekiyor</span><strong>{repairCount}</strong></Link></section>
 <form className="guardianTools"><input aria-label="Veli veya öğrenci ara" name="q" defaultValue={query.q||""} placeholder="Veli, kursiyer, telefon veya öğrenci ara"/><select aria-label="Portal durumu" name="status" defaultValue={status}><option value="all">Tüm hesaplar</option><option value="active">Portal aktif</option><option value="pending">İlk giriş bekleniyor</option><option value="inactive">Pasif portal</option><option value="unlinked">Öğrencisiz hesap</option><option value="repair">Onarım gerekiyor</option></select><select aria-label="Öğrenci bağlantısı" name="link" defaultValue={linkFilter}><option value="all">Tüm bağlantılar</option><option value="multiple">Birden fazla öğrenci</option><option value="single">Tek öğrenci</option></select><select aria-label="Şube" name="branch" defaultValue={branchFilter}><option value="">Tüm şubeler</option>{(branchesRes.data||[]).map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select aria-label="Grup" name="group" defaultValue={groupFilter}><option value="">Tüm gruplar</option>{(groupsRes.data||[]).map((g:any)=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button className="guardianButton primary"><GuardianIcon name="filter"/>Filtrele</button><Link className="guardianButton" href="/veliler">Temizle</Link></form>
 <div className="guardianListHeading"><h2>Veli hesapları <span>{rows.length}</span></h2><p>Öğrenci bağlantısı, portal erişimi ve iletişim işlemleri</p></div>
 <section className="guardianGrid">{rows.map((g:any)=><article className={`guardianCard ${g.needsRepair?"needsRepair":""}`} key={g.id}><div className="guardianCardHead"><div className="guardianIdentity"><span className="guardianAvatar">{String(g.full_name||"V").slice(0,1).toUpperCase()}</span><div><h2>{g.full_name||"İsimsiz Hesap"}</h2><p>{g.phone||"Telefon yok"}{g.email?` · ${g.email}`:""}</p></div></div><span className={`guardianPill ${!g.portalEnabled?"off":!g.last_sign_in_at?"waiting":""}`}>{!g.portalEnabled?"Portal Pasif":g.last_sign_in_at?"Portal Aktif":"İlk Giriş Bekleniyor"}</span></div>
 <div className="guardianHealthRow">{!g.guardianRecord?<span className="guardianHealth warning">Ana portal kaydı eksik</span>:null}{g.guardianRecord&&g.links.length===0?<span className="guardianHealth danger">Öğrenci bağlantısı eksik</span>:null}{g.guardianRecord&&g.links.length>0?<span className="guardianHealth ok">{g.links.length} öğrenci bağlı</span>:null}</div>
 <div className="guardianChildren">{g.links.map((l:any)=>{const s:any=studentMap.get(l.student_id),e:any=enrollmentMap.get(l.student_id),gr:any=groupMap.get(e?.group_id||s?.preferred_group_id),br:any=branchMap.get(gr?.branch_id||s?.branch_id);return <div className="guardianChild" key={l.student_id}><span><b>{s?`${s.first_name} ${s.last_name}`:"Öğrenci bulunamadı"}</b><small>{br?.name||"Şube yok"} · {gr?.name||"Grup yok"}</small></span><span className="guardianChildActions"><small>{l.relationship||"Veli"}{l.is_primary?" · Birincil":""}</small><Link className="guardianStudentFileButton" href={`/ogrenciler/${l.student_id}`}><GuardianIcon name="file"/>Öğrenci Dosyası</Link>{canDelete?<UnlinkStudentButton profileId={g.id} studentId={l.student_id} name={s?`${s.first_name} ${s.last_name}`:"Öğrenci"}/>:null}</span></div>})}{!g.links.length?<div className="guardianChild"><small>Henüz öğrenci bağlantısı yok. Portal dosyasından öğrenci bağlayabilirsiniz.</small></div>:null}</div>
 <div className="guardianCardActions"><Link className="guardianMainAction" href={`/veliler/${g.id}`}><GuardianIcon name="shield"/>Veli Dosyasını Yönet<GuardianIcon name="arrow"/></Link><Link href={`/veliler/${g.id}#ogrenci-baglantilari`}><GuardianIcon name="users"/>Öğrenci Bağlantıları</Link></div>
 <GuardianPortalActions guardianProfileId={g.id} phone={g.phone||""} hasGuardianRow={Boolean(g.guardianRecord)} linkedCount={g.links.length}/>
 {canDelete?<details className="guardianDangerZone"><summary>Hesap silme işlemi</summary><p>Tüm öğrenci bağlantılarını kaldırır ve portal hesabını siler. Tek bir yanlış bağlantı için öğrencinin “Bağlantıyı Kaldır” butonunu kullanın.</p><DeleteGuardianButton guardianId={g.id} name={g.full_name||"Bu hesap"}/></details>:null}
 </article>)}{!rows.length?<div className="guardianEmpty">Aramanıza uygun portal hesabı bulunamadı.</div>:null}</section>
 </div></main></>;
}
